spring:
  application:
    name:
      backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kodb
    password: ${MYSQL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true